### ISSUE TITLE
Implement singularity

### ISSUE THREAD

**Issue by mgalland** [KoesGroup/Snakemake_ChIPseq_PE#6]
Add singularity management within Snakemake.

From the documentation:
>Singularity enables users to have full control of their environment. Singularity containers can be used to package entire scientific workflows, software and libraries, and even data. This means that you don’t have to ask your cluster admin to install anything for you - you can put it in a Singularity container and run.

**Comment by JihedC** [comment]
I think we just need to add this on top of the snakefile : 

`singularity: "docker://continuumio/miniconda3"`

and run the snakefile using : `--use-conda --use-singularity`

**Comment by mgalland** [comment]
Implemented like a boss!
